// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQmndJkBrUymdIxxGr7rL26turoj6fu98',
    appId: '1:277550183303:web:6b3d86397c5ddc8dd45922',
    messagingSenderId: '277550183303',
    projectId: 'assignment-60ac1',
    authDomain: 'assignment-60ac1.firebaseapp.com',
    storageBucket: 'assignment-60ac1.appspot.com',
    measurementId: 'G-XSVZ1LGRWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd9-wzHqJJC3Ni-xe2JOPLoMYKiTjCD3o',
    appId: '1:277550183303:android:05040652b6f4cb94d45922',
    messagingSenderId: '277550183303',
    projectId: 'assignment-60ac1',
    storageBucket: 'assignment-60ac1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ajJXTw9hfTCniQqmT1F6ZltpJysWCjk',
    appId: '1:277550183303:ios:ba182465f1efdfc6d45922',
    messagingSenderId: '277550183303',
    projectId: 'assignment-60ac1',
    storageBucket: 'assignment-60ac1.appspot.com',
    iosClientId: '277550183303-1m51jjj4p41es8v9bomu1ksc7mmm1ks5.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ajJXTw9hfTCniQqmT1F6ZltpJysWCjk',
    appId: '1:277550183303:ios:4c4920158b455c39d45922',
    messagingSenderId: '277550183303',
    projectId: 'assignment-60ac1',
    storageBucket: 'assignment-60ac1.appspot.com',
    iosClientId: '277550183303-eecvb9b070fcqe8fu7msi20ih3ks4trr.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment.RunnerTests',
  );
}
